const mongoose = require('mongoose');
const Schema = mongoose.Schema;

const resumeSchema = new Schema({
  id: String,
  info: String,
  organization: String,
  event: String,
  dates: String,
  resumeType: String,
  conventionServicesRepresentative: String,
  cateringRepresentative: String,
  salesRepresentative: String,
  meetingOverview: String,
  summary: String,
  attendance: String,
  numberOfGuests: String,
  percentageOfSpousalAttendance: String,
  repeatEvent: String,
  keyMeetingContacts: String,
  name: String,
  title: String,
  mobile: String,
  email: String,
  offSiteActivities: String,
  dayandDate: String,
  time: String,
  eventNumberofPeople: String,
  location: String,
  transportationDeparturePoint: String,
  shuttleSchedules: String,
  dayandDate: String,
  time: String,
  numberofVehicles: String,
  frequency: String,
  destination: String,
  executives: String,
  name: String,
  title: String,
  dates: String,
  amenities: String,
  preferences: String,
  authorizedSignatures: String,
  authorizedSignerName: String,
  masterAccount: String,
  whichCharges: String
});

module.exports = mongoose.model('Resume', resumeSchema);
